import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minWidth: 0,
  } satisfies CSSProperties,
  skeletonWrap: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  summaryRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 18,
    margin: 0,
    padding: 0,
    listStyle: "none",
    fontSize: 13.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  stat: { display: "flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  statNumber: { color: "var(--text-primary)", fontWeight: 700 } satisfies CSSProperties,
  muted: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  symbolList: { display: "flex", flexDirection: "column", gap: 8, margin: 0, padding: 0, listStyle: "none" } satisfies CSSProperties,
  symbolBox: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  symbolHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "9px 12px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13.5,
    textAlign: "left",
  } satisfies CSSProperties,
  symbolName: { fontFamily: "var(--font-mono, monospace)", fontWeight: 600 } satisfies CSSProperties,
  wholeFileTag: {
    fontSize: 11,
    color: "var(--text-muted)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: "0 5px",
  } satisfies CSSProperties,
  callerCount: { marginLeft: "auto", color: "var(--text-muted)", fontSize: 12.5, whiteSpace: "nowrap" } satisfies CSSProperties,
  panel: { display: "flex", flexDirection: "column", gap: 10, padding: "4px 12px 12px 32px" } satisfies CSSProperties,
  callerList: { display: "flex", flexDirection: "column", gap: 4, margin: 0, padding: 0, listStyle: "none" } satisfies CSSProperties,
  callerItem: { display: "flex", alignItems: "center", gap: 6, fontSize: 12.5, minWidth: 0 } satisfies CSSProperties,
  callerLink: {
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--accent-text)",
    textDecoration: "none",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  plainNote: { margin: 0, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  chipsLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6 } satisfies CSSProperties,
  chipEndpoint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    maxWidth: "100%",
    padding: "2px 8px",
    borderRadius: 999,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  chipCron: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    maxWidth: "100%",
    padding: "2px 8px",
    borderRadius: 999,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    background: "var(--warn-bg)",
    color: "var(--warn)",
  } satisfies CSSProperties,
  chipText: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  notice: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  noticeWarn: { background: "var(--warn-bg)", borderColor: "var(--warn)" } satisfies CSSProperties,
  noticeBody: { display: "flex", flexDirection: "column", gap: 4, minWidth: 0, flex: 1 } satisfies CSSProperties,
  noticeTitle: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  noticeFiles: { margin: 0, paddingLeft: 16, fontFamily: "var(--font-mono, monospace)", fontSize: 12, overflowWrap: "anywhere", wordBreak: "break-word" } satisfies CSSProperties,
  footer: { margin: 0, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  moreRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
} as const;
